apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: portfolio-site
        image: my-portfolio:v1 # Твой новый образ!
        imagePullPolicy: IfNotPresent # Важно! Чтобы Кубер не лез в интернет за образом
        ports:
        - containerPort: 80
        # --- ВОТ СЮДА ДОБАВЛЯЕМ ---
        readinessProbe:
          httpGet:      # Как проверять? Делать HTTP запрос
            path: /     # Куда? На главную страницу
            port: 80    # На какой порт?
          initialDelaySeconds: 1 # Подождать 5 сек после старта, прежде чем проверять
          periodSeconds: 1       # Проверять каждые 5 секунд
        
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2 # Даем приложению больше времени «раскочегариться»
          periodSeconds: 10